spring:
  application:
    name: callme
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://192.168.0.100:8080/realms/gwrealm/protocol/openid-connect/certs

logging.level:
  org.keycloak: DEBUG
  org.springframework.cloud.gateway: DEBUG
  org.springframework.security: DEBUG
  org.springframework.web.reactive.function.client: TRACE

server.port: 8040